### ISSUE TITLE
We need a getAllVectors() method in VectorArea!

### ISSUE THREAD

**Issue by THEGOLDENPRO** [NovaUniverse/NovaCore#34]
As the title states, we need a getAllVectors() method in VectorArea. It would be very nice if we could get the vector of each block in a vector area. 

There is a method to get the vector of each block outline of the area so I don't see why we can't have a method to get every vector in the area too.

https://github.com/NovaUniverse/NovaCore/blob/227572aadb2f67a4b6f3f0ea02cbdf7cadece229/NovaCore-Spigot/src/main/java/net/zeeraa/novacore/spigot/utils/VectorArea.java#L130

**Comment by BrunoGamerGH** [comment]
no :trollface:

**Comment by THEGOLDENPRO** [comment]
> no :trollface:

shush

**Comment by BrunoGamerGH** [comment]
> > no :trollface:
> 
> 
> 
> shush

:trollface:

**Comment by AntonUden** [comment]
Implemented in latest build
